// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NumberSortApp.Data;

#nullable disable

namespace NumberSortApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NumberSortApp.Models.SortNumber", b =>
                {
                    b.Property<string>("SortedNumbers")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SortingDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("SortingTime")
                        .HasColumnType("time");

                    b.HasKey("SortedNumbers");

                    b.ToTable("SortModels");
                });
#pragma warning restore 612, 618
        }
    }
}
